/*******************************************************************************
* File Name: app_Ble.c
*
* Description:
*  Common BLE application code for client devices.
*
*******************************************************************************
* Copyright 2015, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "app_ble.h"
#include "debug.h"

#include "app_SPI.h"

/* size to be used by Client and Server after MTU exchange */
uint16 mtuSize      = CYBLE_GATT_MTU;

/*******************************************************************************
* Function Name: HandleBleProcessing
********************************************************************************
*
* Summary:
*   Handles the BLE state machine for intiating different procedures
*   during different states of BLESS.
*
* Parameters:
*   None.
*
* Return:
*   None.
*
*******************************************************************************/
void HandleBleProcessing(void)
{    
    uint8 txDataClientConfigDesc[2];
   
    CYBLE_GATT_HANDLE_VALUE_PAIR_T  attrValue = { 
                                                    {(uint8 *)txDataClientConfigDesc, 2, 2}, 
                                                    CYBLE_COMMUNICATION_RX_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE
                                                };
    switch (cyBle_state)
    {
        case CYBLE_STATE_ADVERTISING:
            break;
        
        case CYBLE_STATE_CONNECTED:
            
            /* read CCCD for TX characteristic for checking if notifications are enabled*/
            CyBle_GattsReadAttributeValue(&attrValue, &cyBle_connHandle, CYBLE_GATT_DB_LOCALLY_INITIATED);
            
            /* if stack is free, handle UART && SPI traffic */
            if(CyBle_GattGetBusStatus() != CYBLE_STACK_STATE_BUSY)
            {
                HandleUartTxTraffic((uint16)txDataClientConfigDesc[0]);
                
                HandleSPITraffic();
            }
            break;
                
        case CYBLE_STATE_DISCONNECTED:
        
            txDataClientConfigDesc[0] = NOTIFICATON_DISABLED;
            txDataClientConfigDesc[1] = NOTIFICATON_DISABLED;
            
            //CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);

            break;
       
        case CYBLE_STATE_INITIALIZING:
        case CYBLE_STATE_STOPPED:
        default:
            break;       
    }
}


/*******************************************************************************
* Function Name: AppCallBack
********************************************************************************
*
* Summary:
*   Call back function for BLE stack to handle BLESS events
*
* Parameters:
*   event       - the event generated by stack
*   eventParam  - the parameters related to the corresponding event
*
* Return:
*   None.
*
*******************************************************************************/
void AppCallBack(uint32 event, void *eventParam)
{   
    CYBLE_API_RESULT_T              apiResult;
    CYBLE_GATT_ERR_CODE_T           errorCode;
    CYBLE_GATTS_WRITE_REQ_PARAM_T   *writeReqParam;
    
    switch (event)
    {
        case CYBLE_EVT_STACK_ON:
            DBG_PRINTF("EVT_STACK_ON: Starting advertisement\r\n");
            /* Enter in to discoverable mode so that remote can search it. */
            apiResult = CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            if(apiResult != CYBLE_ERROR_OK)
            {
            }
            
            break;
            
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED:
            DBG_PRINTF("EVT_GAP_DEVICE_DISCONNECTED\r\n");
            
            while(0 != (UART_SpiUartGetTxBufferSize() + UART_GET_TX_FIFO_SR_VALID));        
            
            apiResult = CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            if(apiResult != CYBLE_ERROR_OK)
            {
                DBG_PRINTF("StartAdvertisement API Error: %d \r\n", apiResult);
            }
            
            /* RESET Uart and flush all buffers */
            UART_Stop();
            UART_SpiUartClearTxBuffer();
            UART_SpiUartClearRxBuffer();
            UART_Start();
            break;
            
        case CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP:
            DBG_PRINTF("CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP\r\n");
            if(CYBLE_STATE_DISCONNECTED == CyBle_GetState())
            {   
                /* Fast and slow advertising period complete, go to low power  
                 * mode (Hibernate mode) and wait for an external
                 * user event to wake up the device again */
                DBG_PRINTF("Entering low power mode...\r\n");
                //Bootloading_LED_Write(LED_ON);
                //Advertising_LED_Write(LED_ON);
                //Bootloader_Service_Activation_ClearInterrupt();
                //Wakeup_Interrupt_ClearPending();
                //Wakeup_Interrupt_Start();
                CySysPmHibernate();
            }
            break;
            
        case CYBLE_EVT_GATT_CONNECT_IND:
            DBG_PRINTF("EVT_GATT_CONNECT_IND Connection established\r\n");
            
            connectionIndHandlerForSecurity();
            
            break;
        
        case CYBLE_EVT_GATTS_WRITE_CMD_REQ:
            DBG_PRINTF("EVT_GATTS_WRITE_CMD_REQ \r\n");
            HandleUartRxTraffic((CYBLE_GATTS_WRITE_REQ_PARAM_T *) eventParam);    
            
            writeReqParam = (CYBLE_GATTS_WRITE_REQ_PARAM_T *) eventParam;
            
            if( CYBLE_SECURITY_SECURITY_CONTROL_CHAR_HANDLE == \
                                                                    writeReqParam->handleValPair.attrHandle ) {
                                                               
                // CMD_REQ handler for Security Service
                cmdWriteReqHandlerForSecurity(writeReqParam->handleValPair.value.val, writeReqParam->handleValPair.value.len);
            }
                                                                    
            break;
        
        case CYBLE_EVT_GATTS_XCNHG_MTU_REQ:
            DBG_PRINTF("EVT_GATTS_XCNHG_MTU_REQ \r\n");
            if(CYBLE_GATT_MTU > ((CYBLE_GATT_XCHG_MTU_PARAM_T *)eventParam)->mtu)
            {
                mtuSize = ((CYBLE_GATT_XCHG_MTU_PARAM_T *)eventParam)->mtu;
            }
            else
            {
                mtuSize = CYBLE_GATT_MTU;
            }
            
            break;
            
        case CYBLE_EVT_GATTS_WRITE_REQ:
            
            writeReqParam = (CYBLE_GATTS_WRITE_REQ_PARAM_T *) eventParam;
            
            if(CYBLE_COMMUNICATION_RX_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE == \
                                                                    writeReqParam->handleValPair.attrHandle)
            {
                DBG_PRINTF("*****Communication Service write request***** \r\n");
                
                errorCode = CyBle_GattsWriteAttributeValue(&(writeReqParam->handleValPair), \
                                                0, &cyBle_connHandle, CYBLE_GATT_DB_PEER_INITIATED);
                
                if (CYBLE_GATT_ERR_NONE  == errorCode)
                {
                    CyBle_GattsWriteRsp(cyBle_connHandle);
                    
                    DBG_PRINTF("\r\nNotifications enabled\n\r");
                    DBG_PRINTF("Start entering data:\n\r");
                }
            }
            else if(CYBLE_SECURITY_SECURITY_CONTROL_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE == \
                                                                    writeReqParam->handleValPair.attrHandle)
            {
                DBG_PRINTF("*****Security Service write request***** \r\n");
                
                errorCode = CyBle_GattsWriteAttributeValue(&(writeReqParam->handleValPair), \
                                                0, &cyBle_connHandle, CYBLE_GATT_DB_PEER_INITIATED);
                
                if (CYBLE_GATT_ERR_NONE  == errorCode)
                {
                    CyBle_GattsWriteRsp(cyBle_connHandle);
                    
                    DBG_PRINTF("\r\nNotifications enabled\n\r");
                }
            }
            
            break;
        
        default:
            break;
    }
}

/* [] END OF FILE */
